### ISSUE TITLE
Mail dependency (via savon-multipart)

### ISSUE THREAD

**Issue by azyzio** [espago/gus_bir1#3]
Hi guys,

Thanks a lot creating the gem. It is very niche, but very time-saving for those who need this :)

Can you see any way to use it without gem compatibility issues when on newer versions of rails? A lot of big gems depend on mail, which is now in version 2.7.1. Savon-multipart requires  ~>2.5.4

Downgrading mail this much required downgrading many other gems too as therefore introduces potential security issues

Thanks and best,
Adam

**Comment by wacaw** [comment]
Fixed in version 1.1.0.

**Comment by azyzio** [comment]
Thanks! All working great :)
